# These are supported funding model platforms

custom: ['https://www.fiverr.com/creativitas/design-your-website-with-phyton-django','https://www.hockeycomputindo.com/2010/12/blog-post.html','https://axcora.com/sourcecode/','https://axcora.com/getaxcoracms']
