# Generated by Django 3.2.9 on 2021-11-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cover', models.CharField(max_length=500)),
                ('section1', models.TextField()),
                ('imgsection1', models.CharField(max_length=500)),
                ('section2', models.TextField()),
                ('imgsection2', models.CharField(max_length=500)),
                ('imgfooter', models.CharField(max_length=500)),
                ('footer', models.TextField()),
            ],
        ),
    ]
